# Generated by Django 3.1.5 on 2021-01-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210112_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='storeName',
            field=models.CharField(default='tupan', max_length=100),
            preserve_default=False,
        ),
    ]
