# Generated by Django 3.1.5 on 2021-01-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_product_storename'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
