# Generated by Django 3.1.7 on 2021-03-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_product_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
