# Generated by Django 2.2.20 on 2021-04-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_product_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
