# Generated by Django 2.2.20 on 2021-04-15 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_auto_20210415_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('untilDate', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Product')),
            ],
        ),
    ]
