# Generated by Django 2.2.20 on 2021-04-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_productsprices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsprices',
            old_name='productId',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='productsprices',
            name='untilDate',
            field=models.DateField(auto_now=True),
        ),
    ]
