# Generated by Django 3.2.6 on 2021-08-29 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoAL', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='codGetin',
            new_name='codGtin',
        ),
    ]
