# Generated by Django 3.2.5 on 2021-07-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True)),
                ('licitacao', models.CharField(max_length=255)),
                ('unidade', models.CharField(max_length=255)),
                ('idGrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortalComprasGov.grupomaterial')),
            ],
        ),
        migrations.CreateModel(
            name='Material_Historico_Precos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.FloatField()),
                ('data', models.DateField()),
                ('idMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PortalComprasGov.material')),
            ],
            options={
                'unique_together': {('idMaterial', 'preco')},
            },
        ),
    ]
